.\" Copyright (c) 2000 Michael Still (mikal@stillhq.com)
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111,
.\" USA.
.TH CHECKINFO 3  "03 September 2000" "Panda PDF Generator" "Panda PDF Generator Programmer's Manual"
.SH NAME
checkInfo
.SH SYNOPSIS
.B #include <panda.h>
.sp
.BI "void checkInfo();"
.SH DESCRIPTION
The function
.B checkInfo
is an
.B internal
Panda function that is used to determine if an info object exists in the PDF document.
.SH EXAMPLE
.br
Simply use:
.RS
.nf
#include <panda.h>

void checkInfo(pdf *document);
.fi
.RE
.SH AUTHOR
.br
Panda is under development by Michael Still (mikal@stillhq.com). All code is Copyright Michael Still 2000, and is released under the GPL. Code submissions are welcomed. Contact Michael at the address above if you have something you would like to contribute.
.SH BUGS
.br
There are no known bugs in Panda. If you find one, please contact mikal@stillhq.com and let me know.
.SH NOTES ON INTERNAL FUNCTION CALLS
.br
This function is considered an internal Panda function. It is therefore expected that a programmer merely seeking to create a PDF document would never need to call this function. You are welcome to call the function if you feel the need.
.SH VERSION
.br
This information relates to version 0.2 of Panda
