.\" Copyright (c) 2000 Michael Still (mikal@stillhq.com)
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111,
.\" USA.
.TH PANDA 3  "15 July 2000" "Panda PDF Generator" "Panda PDF Generator Spec Compatibility"
.SH SPECIFICATION VERSION
Panda is currently working on version 1.3 of the PDF specification coompilance. A copy of the specification is available for download from http://www.adobe.com
.SH TEXT MODE COMPLIANCE
This document outlines Panda's complicance with the various text modes outlined in the PDF specification version specified above.
.SH TEXT MODES
.br
Character spacing (Tc operator)
.RS
The definition of this operator may be found on page 340 of the PDF specification.

This operator is fully implemented in Panda, and is accessible through the
.B setcharacterspacing (3)
function call in Panda. Note that this attribute is 'sticky' and therefore will not revert to the default if you change font \-\- it must be explicitly changed.

The default value is 0.
.RE

Word spacing (Tw operator)
.RS
The definition of this operator may be found on page 340 of the PDF specification.

This operator is fully implemented in Panda, and is accessible through the
.B setwordspacing (3)
function call in Panda. Note that this attribute is 'sticky' and therefore will not revert to the default if you change font \-\- it must be explicitly changed.

The default value is 0.
.RE

Horizontal Scaling (Tz operator)
.RS
The definition of this operator may be found on page 341 of the PDF specification.

This operator is fully implemented in Panda, and is accessible through the
.B sethorizontalscaling (3)
function call in Panda. Note that this attribute is 'sticky' and therefore will not revert to the default if you change font \-\- it must be explicitly changed.

The default value is 1, meaning 100% of the normal width of the text.
.RE

Leading (TL operator)
.RS
The definition of this operator may be found on page 342 of the PDF specification.

This operator is fully implemented in Panda, and is accessible through the
.B setleading (3)
function call in Panda. Note that this attribute is 'sticky' and therefore will not revert to the default if you change font \-\- it must be explicitly changed.

The default value is 0, meaning no extra space between lines of text.
.RE

Font and size (Tf operator)
.RS
The definition of this operator may be found on page 342 of the PDF specification.

This operator is fully implemented in Panda, and is accessible through the
.B setfont (3)
and
.B setfontsize (3)
function calls in Panda. Note that these attributes are 'sticky' and therefore will not revert to the default if you perform other manipulations. You will need to explicitly change font and size if you wish to.

The default font is Helvetica, with a size of 16 points.
.RE

Text matrix (Tm operator)
.B PARTIALLY IMPLEMENTED
.RS
The definition of this operator may be found on page 342 of the PDF specification.

This operator is partially implemented in Panda (due to my lack of understanding of the meaning of the values in the matrix), and is accessible indirectly through the
.B textbox (3)
function call in Panda. This is because this operator is used to place the textbox onto the page. The default Tm value, is we did not set one in the textbox code, is the bottom left hand corner of the page. The default implemented by the textbox code is the top left hand corner of the page, although the user must set a location on the page for the function call to be valid.
.RE

Text rendering (Tr operator)
.RS
The definition of this operator may be found on page 343 of the PDF specification.

This operator is fully implemented in Panda, and is accessible through the
.B setfontmode (3)
function call in Panda. Note that this attribute is 'sticky' and therefore will not revert to the default if you change font \-\- it must be explicitly changed.

The default mode is gTextModeNormal.
.RE

Super and sub scripting (Ts operator)
.RS
The definition of this operator may be found on page 344 of the PDF specification.

This operator is fully implemented in Panda, and is accessible indirectly through the
.B textbox (3)
function call in Panda. Note that this attribute is
.B not
'sticky' and therefore will revert to the default when you create a new textbox. This attribute is accessed via the text string passed into
.B textbox (3)
. In order to turn on superscripting, place the
.B EOT
character (ASCII value 4) into the string, followed immediately by the jump upwards (as an ASCII single digit number). To subscript, place the
.B ENQ
character (ASCII value 5), followed immediately by the jump downwards (as an ASCII single digit number). To return to the normal text placement, place the
.B ACK
character (ASCII value 6) into the string.

The default is no super or sub scripting.

Some source code that shows this is:
.RS
.nf
sprintf(tempString, "Hello %c5World! %cMy name %c5is Panda!", 4, 6, 5);
.fi
.RE
This code superscripts the text "World!" by 5 points, subscripts the text "is Panda!" by 5 points, and displays the rest in the normal location on the line. Note that you may need to use the text leading functionality to ensure correct display.
.RE

Text object operators (BT and ET operators)
.RS
The definition of these operators may be found on page 344 of the PDF specification.

These operators are implemented in Panda and are accessible implicitly in the 
.B textbox (3)
function call.
.RE

Newline with offset (Td and TD operators)
.B NOT YET IMPLEMENTED

Newline (T* operator)
.B NOT YET IMPLEMENTED

Text rendering matrix (Trm operator)
.B NOT YET IMPLEMENTED

Show text (Tj operator)
.RS
The definition of this operator may be found on page 347 of the PDF specification.

This operator is implicitly implemented in the
.B textbox (3)
function call.
.RE

Show text on new line (' operator)
.RS
The definition of this operator may be found on page 347 of the PDF specification.

This operator is implicitly implemented in the
.B textbox (3)
function call.
.RE

Show text one new line with movement (" operator)
.B NOT YET IMPLEMENTED

Show text with manipulation (TJ operator)
.B NOT YET IMPLEMENTED

.SH AUTHOR
.br
Panda is under development by Michael Still (mikal@stillhq.com). All code is Copyright Michael Still 2000, and is released under the GPL. Code submissions are welcomed. Contact Michael at the address above if you have something you would like to contribute.
.SH BUGS
.br
There are no known bugs in Panda. If you find one, please contact mikal@stillhq.com and let me know.
