.\" Copyright (c) 2000 Michael Still (mikal@stillhq.com)
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111,
.\" USA.
.TH SHS 3 "15 July 2000" "Panda PDF Generator" "Panda PDF Generator Programmer's Manual"
.SH NAME
sethorizontalscaling
.SH SYNOPSIS
.B #include <panda.h>
.sp
.BI "void sethorizontalscaling(pdf *, double scaling);"
.SH DESCRIPTION
The function
.B sethorizontalscaling
sets the space to be used by each character as a fraction of the space it would normally use. For instance, 0.5 scaling would mean use 50% of the space for each character that would normally be used. The value that is set with this call is sticky and will therefore apply to all subsequently created text boxes until the value of the word spacing is changed to something else. The default value for scaling is 1.
.SH EXAMPLE
.br
Simply use:
.RS
.nf
#include <panda.h>

pdf *document;

document = openpdf("filename", "w");
sethorizontalscaling(document, 0.5);
.fi
.RE
.SH AUTHOR
.br
Panda is under development by Michael Still (mikal@stillhq.com). All code is Copyright Michael Still 2000, and is released under the GPL. Code submissions are welcomed. Contact Michael at the address above if you have something you would like to contribute.
.SH BUGS
.br
There are no known bugs in Panda. If you find one, please contact mikal@stillhq.com and let me know.
.SH VERSION
.br
This information relates to version 0.2 of Panda
