#!/bin/bash

# This script makes the world nice-looking for the world.

# Tag this and commit it to cvs
cvs commit

echo "Name this version e.g. panda-release-02"
read $version
cvs tag $version

make clean
rm ./configure

# Get rid of core files
for item in `find . | grep core`
do
  rm -i $item
done

# Get rid of the timetrials -- they are too big
rm -rf timetrials

delname="Makefile config.cache config.log config.status logfile math"

# Get rid of makefiles
for filename in $delname
do
  for item in `find . -name $filename -print`
  do
    rm -i $item
  done
done

# Generate the configure script
autoconf

# How much space do we use?
du -sk







