#!/bin/bash

# This script makes the world nice-looking for the world.

cd man
rm *sgml
cd ..

for item in `ls *.c`
do
  ~mikal/opensource/autodocbook/0.3/autodocbook $item man
done

automake
autoconf
./configure
make clean
make

# Get rid of core files
for item in `find . | grep core`
do
  rm -i $item
done

# Make sure that the release passes some simple dmalloc tests
dmalloc -b -l log -i 100 low
cd examples
./pandademo > /dev/null

if [ `grep "not freed" log | wc -l | tr -d " "` -gt 0 ]
then
  echo ""
  echo ""
  echo "Prospective release failed the memory leak test"
  exit 42
fi

cd ..

# Get rid of compiled files that make clean wont remove
find . -name "*obj" -type f -exec rm -i {} \; -print

# Get rid of the timetrials -- they are too big
rm -rf timetrials
rm -rf testdata

delname="Makefile config.cache config.log config.status logfile math config.h output.pdf .deps"

# Get rid of makefiles
for filename in $delname
do
  for item in `find . -name $filename -print`
  do
    rm -ri $item
  done
done

# How much space do we use?
du -sk


