#!/bin/bash

# This script makes the world nice-looking for the world.

make clean
rm ./configure

# Get rid of core files
for item in `find . | grep core`
do
  rm -i $item
done

delname="Makefile config.cache config.log config.status"

# Get rid of makefiles
for filename in $delname
do
  for item in `find . -name $filename -print`
  do
    rm -i $item
  done
done