#!/bin/bash

# Sometimes we just want to be lazy and make one compression format. See if 
# this is so
if [ `echo $1 | wc -c | tr -d " "` -gt 0 ]
then
  compressionOptions=$1
else
  compressionOptions="none packbits jpeg zip g3 g4"
fi

for endian in B L
do
  for compression in $compressionOptions
  do
    for fill in msb2lsb lsb2msb
    do
      for planar in contig # separate
      do
        for rows in 1 1000 1000000
	do
  	  echo tiffcp -$endian -c $compression -f $fill -p $planar -r $rows input.tif $compression-$endian-$fill-$planar-$rows.tif

  	  tiffcp -$endian -c $compression -f $fill -p $planar -r $rows input.tif $compression-$endian-$fill-$planar-$rows.tif
	done
      done
    done
  done
done